
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AOSInitializer from "@/components/AOSInitializer";
import Home from "./home/page";
import Footer from "./footer/Footer";
import CustomCursor from "@/components/CustomCursor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Az Scientific Solutions",
  description: "Generated by create next app",
  icons: {
    icon: "./AZ Logo.png", // <- path from public folder
  },
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./AZ Logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
        <link href="https://fonts.googleapis.com/css2?family=Winky+Rough:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />

      </head>
      <body
        cz-shortcut-listen="true"


      >
        <div className="mb-4" id="home">
          <Home />
        </div>
        {children}
        <div className="mt-[70px] md:mt-[50px]">

          <Footer />
        </div>
        <CustomCursor />
        <AOSInitializer />
      </body >

    </html>
  );
}
